export const VERIFIED_DATE = 'September 6, 2026';
export const VERIFIED_ISO = '2026-09-06';

export type Source = {
  id: string;
  title: string;
  publisher: string;
  url: string;
  reviewed: string;
  note: string;
};

export const sources: Source[] = [
  {
    id: 'jcps-admissions',
    title: 'McNair & Infinity admissions',
    publisher: 'Jersey City Public Schools / MS #7 counseling',
    url: 'https://sites.google.com/jcboe.org/ms-7-high-school-options/home/mcnair-infinity',
    reviewed: 'October 9, 2026',
    note: 'Most recently published application dates, selection weights, and recommendation guidance (still the 2026–27 cycle).',
  },
  {
    id: 'jcboe-admissions-criteria',
    title: 'August 27, 2026 board minutes: Resolution 12.03, specialized admission school criteria',
    publisher: 'Jersey City Board of Education',
    url: 'https://go.boarddocs.com/nj/jcps/Board.nsf/files/DXWRZD706756/$file/August%2027%2C%202026%20-%20Regular%20Meeting%20Minutes.pdf',
    reviewed: 'October 9, 2026',
    note: 'Board approval of revised McNair and Infinity admissions criteria for applications for the 2027–28 school year, with the recorded vote. The revised criteria themselves are not attached.',
  },
  {
    id: 'doj-mcnair',
    title: 'Settlement on McNair Academic High School admissions',
    publisher: 'U.S. Department of Justice',
    url: 'https://www.justice.gov/opa/pr/justice-department-announces-end-illegal-dei-admissions-practices-jersey-city-college-prep',
    reviewed: 'October 9, 2026',
    note: 'July 9, 2026 announcement that the district will stop reserving McNair seats by race or national origin and adopt a new admissions policy before the 2027–28 admissions cycle.',
  },
  {
    id: 'jcps-psat',
    title: 'PSAT 8/9 guidance',
    publisher: 'Jersey City Public Schools / MS #7 counseling',
    url: 'https://sites.google.com/jcboe.org/ms-7-high-school-options/home/psat-89',
    reviewed: VERIFIED_DATE,
    note: 'Local test guidance for the most recently completed admissions cycle.',
  },
  {
    id: 'jcps-hip',
    title: 'JCPS High School Initiative Program application overview',
    publisher: 'Jersey City Public Schools / MS #7 counseling',
    url: 'https://sites.google.com/jcboe.org/ms-7-high-school-options/home/jersey-city-public-schools',
    reviewed: VERIFIED_DATE,
    note: 'Latest published HIP process, district academy choices, Innovation lottery, Liberty interview, and prior-cycle dates.',
  },
  {
    id: 'jcps-high-schools',
    title: 'Jersey City public high schools directory',
    publisher: 'Jersey City Public Schools',
    url: 'https://www.jcboe.org/apps/pages/index.jsp?pREC_ID=1670255&type=d&uREC_ID=1537124',
    reviewed: VERIFIED_DATE,
    note: 'Official district list of comprehensive, small, selective, and alternative high schools.',
  },
  {
    id: 'jcps-cte',
    title: 'Career and Technical Education programs',
    publisher: 'Jersey City Public Schools',
    url: 'https://www.jcboe.org/apps/pages/index.jsp?pREC_ID=1796215&type=d&uREC_ID=1537407',
    reviewed: VERIFIED_DATE,
    note: 'Current district CTE pathways, certifications, and school locations.',
  },
  {
    id: 'innovation-home',
    title: 'Innovation High School overview',
    publisher: 'Innovation High School / Jersey City Public Schools',
    url: 'https://ihs.jcboe.org/',
    reviewed: VERIFIED_DATE,
    note: 'Current school mission, contact information, activities, and announcements.',
  },
  {
    id: 'liberty-home',
    title: 'Liberty High School overview',
    publisher: 'Liberty High School / Jersey City Public Schools',
    url: 'https://lhs.jcboe.org/',
    reviewed: VERIFIED_DATE,
    note: 'Current description of Liberty’s small-school model, mission, and programs.',
  },
  {
    id: 'college-board',
    title: 'Fall 2026 in-school score release dates',
    publisher: 'College Board',
    url: 'https://satsuite.collegeboard.org/scores/score-release-dates',
    reviewed: VERIFIED_DATE,
    note: 'Official fall 2026 in-school testing window and score release schedule.',
  },
  {
    id: 'nj-performance',
    title: 'New Jersey School Performance Reports',
    publisher: 'New Jersey Department of Education',
    url: 'https://www.nj.gov/education/schoolperformance/',
    reviewed: VERIFIED_DATE,
    note: 'State source for enrollment, outcomes, coursework, and school context.',
  },
  {
    id: 'hcst-admissions',
    title: 'High school admissions',
    publisher: 'Hudson County Schools of Technology',
    url: 'https://hcstonline.org/admissions/',
    reviewed: 'September 20, 2026',
    note: 'Official 2027–28 application deadlines, grade and residency eligibility, open houses, portfolio and audition requirements, and selection criteria.',
  },
  {
    id: 'high-tech-academies',
    title: 'High Tech academies',
    publisher: 'High Tech High School',
    url: 'https://hths.hcstonline.org/academies/',
    reviewed: VERIFIED_DATE,
    note: 'Official overview of six academy groupings.',
  },
  {
    id: 'high-tech-academics',
    title: 'High Tech academic program',
    publisher: 'High Tech High School',
    url: 'https://hths.hcstonline.org/about-us/',
    reviewed: VERIFIED_DATE,
    note: 'Core academic requirements, AP examples, and LEAP information.',
  },
  {
    id: 'county-prep-programs',
    title: 'County Prep career and technical programs',
    publisher: 'County Prep High School',
    url: 'https://cphs.hcstonline.org/programs-of-study/careertechnicalprogram/',
    reviewed: VERIFIED_DATE,
    note: 'Current school-published list of CTE majors.',
  },
  {
    id: 'county-prep-academics',
    title: 'County Prep academics',
    publisher: 'County Prep High School',
    url: 'https://cphs.hcstonline.org/programs-of-study/academics/',
    reviewed: VERIFIED_DATE,
    note: 'Graduation requirements and academic program overview.',
  },
  {
    id: 'county-prep-ap',
    title: 'County Prep AP courses',
    publisher: 'County Prep High School',
    url: 'https://cphs.hcstonline.org/programs-of-study/ap-courses/',
    reviewed: VERIFIED_DATE,
    note: 'School-published AP course list.',
  },
  {
    id: 'sda-home',
    title: 'Saint Dominic Academy overview',
    publisher: 'Saint Dominic Academy',
    url: 'https://saintdoms.org/',
    reviewed: 'October 2, 2026',
    note: 'Current school profile and programs; the September 27, 2026 fall open house (now past) and links to schedule tours and DOMS for a Day student visits.',
  },
  {
    id: 'sda-apply',
    title: 'How to apply',
    publisher: 'Saint Dominic Academy',
    url: 'https://saintdoms.org/admissions/how-to-apply/',
    reviewed: 'September 23, 2026',
    note: 'Application steps, documents, and most recently published entrance-exam guidance.',
  },
  {
    id: 'sda-tuition',
    title: '2026–27 tuition and aid',
    publisher: 'Saint Dominic Academy',
    url: 'https://saintdoms.org/admissions/tuition/',
    reviewed: VERIFIED_DATE,
    note: 'Current tuition, fees, payment options, scholarships, and assistance information.',
  },
  {
    id: 'hudson-catholic-apply',
    title: 'Freshman application requirements',
    publisher: 'Hudson Catholic Regional High School',
    url: 'https://hudsoncatholic.org/apply',
    reviewed: VERIFIED_DATE,
    note: 'Application, HSPT, report-card, recommendation, interview, scholarship, and aid guidance.',
  },
  {
    id: 'hudson-catholic-tuition',
    title: '2026–27 tuition and fees',
    publisher: 'Hudson Catholic Regional High School',
    url: 'https://hudsoncatholic.org/tuition-fees',
    reviewed: VERIFIED_DATE,
    note: 'Published tuition, required fees, payment plans, and financial-aid treatment.',
  },
  {
    id: 'hudson-catholic-courses',
    title: 'Academic course offerings',
    publisher: 'Hudson Catholic Regional High School',
    url: 'https://hudsoncatholic.org/course-offerings',
    reviewed: VERIFIED_DATE,
    note: 'Most recently published subject, honors, AP, dual-credit, arts, and applied-course list.',
  },
  {
    id: 'spprep-dates',
    title: 'Class of 2031 admissions dates',
    publisher: 'Saint Peter’s Prep',
    url: 'https://spprep.org/admissions/important-dates/',
    reviewed: 'September 23, 2026',
    note: 'Confirmed application, visit, open-house, HSPT, financial-aid, completion, and decision dates.',
  },
  {
    id: 'coop-hspt',
    title: '2026–2027 Cooperative Admissions HSPT important dates',
    publisher: 'Archdiocese of Newark / Diocese of Paterson COOP program',
    url: 'https://www.njcoopexam.org/docs/115-2026-IMPORTANT-DATES.pdf',
    reviewed: 'September 23, 2026',
    note: 'Official November 6, 2026 HSPT date, November 14 makeup, and October registration deadlines for current eighth graders applying to participating Catholic high schools.',
  },
  {
    id: 'spprep-tuition',
    title: '2026–27 tuition and fees',
    publisher: 'Saint Peter’s Prep',
    url: 'https://spprep.org/admissions/tuition-fees-at-a-glance/',
    reviewed: VERIFIED_DATE,
    note: 'Current tuition, mandatory fees, payment plans, scholarship, and financial-aid overview.',
  },
  {
    id: 'spprep-academics',
    title: 'Academic program',
    publisher: 'Saint Peter’s Prep',
    url: 'https://spprep.org/academics/',
    reviewed: VERIFIED_DATE,
    note: 'Current departments, curriculum resources, counseling, and advanced-course information.',
  },
  {
    id: 'uachs-apply',
    title: 'New student application',
    publisher: 'University Academy Charter High School',
    url: 'https://www.uachs.org/apps/pages/welcome',
    reviewed: VERIFIED_DATE,
    note: 'Open-enrollment policy, latest application deadline, lottery process, and submission methods.',
  },
  {
    id: 'uachs-profile',
    title: 'School profile',
    publisher: 'University Academy Charter High School',
    url: 'https://www.uachs.org/apps/pages/schoolprofile',
    reviewed: VERIFIED_DATE,
    note: 'Current school size, small-class model, service learning, and journalism focus.',
  },
  {
    id: 'uachs-courses',
    title: 'Course catalog',
    publisher: 'University Academy Charter High School',
    url: 'https://www.uachs.org/apps/pages/coursecatalog',
    reviewed: VERIFIED_DATE,
    note: 'Current and recently approved AP, engineering, robotics, agriculture, journalism, and dual-credit courses.',
  },
  {
    id: 'beloved-apply',
    title: '2027–28 application and lottery',
    publisher: 'BelovED Community Charter School',
    url: 'https://www.belovedccs.org/apply/apply_to_enroll_your_child',
    reviewed: 'October 9, 2026',
    note: 'Confirmed October 15 application opening, January 15 deadline, annual lottery, and wait-list policy.',
  },
  {
    id: 'beloved-visit',
    title: 'Open houses',
    publisher: 'BelovED Community Charter School',
    url: 'https://www.belovedccs.org/apply/visit',
    reviewed: 'October 9, 2026',
    note: 'Published 2026–27 open-house schedule by grade band, including the October 22, 2026 virtual and January 28, 2027 in-person grades 9–12 open houses; no appointment required.',
  },
  {
    id: 'beloved-curriculum',
    title: 'Curriculum and instruction',
    publisher: 'BelovED Community Charter School',
    url: 'https://www.belovedccs.org/academics__activities/curriculum___instruction',
    reviewed: VERIFIED_DATE,
    note: 'Official instructional model and notice that the detailed 2026–27 high-school curriculum page is still being updated.',
  },
];

export type School = {
  slug: string;
  name: string;
  shortName: string;
  type: string;
  system: string;
  location: string;
  cost: string;
  test: string;
  eligibility: string;
  accent: string;
  summary: string;
  bestFor: string;
  tradeoff: string;
  admissionsStatus: string;
  admissions: string[];
  academics: string[];
  programs: string[];
  questions: string[];
  facts: { label: string; value: string }[];
  sourceIds: string[];
};

export const schools: School[] = [
  {
    slug: 'mcnair-academic',
    name: 'Dr. Ronald E. McNair Academic High School',
    shortName: 'McNair Academic',
    type: 'Selective academic magnet',
    system: 'Jersey City Public Schools',
    location: '123 Coles Street, Jersey City',
    cost: 'Public · no tuition',
    test: 'PSAT 8/9 required',
    eligibility: 'Jersey City residents entering grade 9',
    accent: 'orange',
    summary: 'The broadest traditional college-preparatory option in this group, with a large advanced-course ecosystem and an academically concentrated student body.',
    bestFor: 'Students who want academic breadth, many advanced-course choices, and a larger high-achieving peer community.',
    tradeoff: 'The pace and competition may feel intense; families should ask directly about workload, support, and student stress.',
    admissionsStatus: 'The 2027–28 application window has not yet been published. In August 2026 the Board of Education approved revised McNair and Infinity admissions criteria for 2027–28 applications, but JCPS has not yet published them. Prepare using the latest published formula and watch JCPS announcements for changes.',
    admissions: [
      'On August 27, 2026, the Jersey City Board of Education approved revised McNair and Infinity admissions criteria for applications for the 2027–28 school year. The revision ends the practice of dividing applications by race, following a July 2026 agreement with the U.S. Department of Justice. The revised criteria have not been published yet, so ask JCPS whether any of the weights below have changed.',
      'The latest published formula (2026–27 cycle) weights PSAT 8/9 scores at 40% and grades from grades 6–8 at 40%.',
      'Teacher recommendations account for 10%; attendance and extracurricular activities account for 5% each.',
      'The most recent cycle opened November 26, 2025, closed December 23, and sent decisions January 23, 2026. Those dates are a planning reference—not confirmed 2027–28 deadlines.',
      'Use a personal family email for the application and line up three teachers who know the student well, following the latest JCPS counseling guidance.',
    ],
    academics: [
      'A rigorous college-preparatory curriculum with substantial Advanced Placement breadth.',
      'Best understood as a general academic magnet rather than a four-year career-major school.',
      'NJDOE performance reports are the recommended source for current enrollment, outcomes, course participation, and student-group context.',
    ],
    programs: ['Broad AP course access', 'Research and critical-thinking emphasis', 'Academic clubs and extracurriculars', 'Traditional four-year high school setting'],
    questions: ['How many hours of homework are typical by grade?', 'How are AP seats and course conflicts handled?', 'What academic and wellness support is available?', 'How easy is it to balance clubs, arts, and athletics with coursework?'],
    facts: [
      { label: 'Admissions focus', value: '80% grades + PSAT' },
      { label: 'School model', value: 'Grades 9–12' },
      { label: 'Defining strength', value: 'Academic breadth' },
    ],
    sourceIds: ['jcps-admissions', 'jcboe-admissions-criteria', 'doj-mcnair', 'jcps-psat', 'college-board', 'nj-performance'],
  },
  {
    slug: 'infinity-institute',
    name: 'Infinity Institute',
    shortName: 'Infinity Institute',
    type: 'Small selective academic magnet',
    system: 'Jersey City Public Schools',
    location: '222 Mercer Street, Jersey City',
    cost: 'Public · no tuition',
    test: 'PSAT 8/9 required',
    eligibility: 'Jersey City residents entering grade 9',
    accent: 'gold',
    summary: 'A very small grades 6–12 academic magnet that pairs serious college preparation with a more intimate, personalized school community.',
    bestFor: 'Students who thrive when teachers know them well and who prefer a small academic community to a large course-and-activity ecosystem.',
    tradeoff: 'A small school inevitably offers fewer sections, scheduling combinations, teams, and clubs than a larger high school.',
    admissionsStatus: 'The 2027–28 application window has not yet been published. The process is shared with McNair, and in August 2026 the Board of Education approved revised criteria for both schools for 2027–28 applications. JCPS has not yet published them.',
    admissions: [
      'Infinity and McNair use one shared selective admissions framework in the latest JCPS guidance.',
      'On August 27, 2026, the Board of Education approved revised admissions criteria for McNair and Infinity for applications for the 2027–28 school year, removing the division of applications by race. The revised criteria are not yet published.',
      'The latest published weighting (2026–27 cycle) is 40% PSAT 8/9, 40% grades, 10% teacher recommendations, 5% attendance, and 5% extracurricular activities. Confirm whether it still applies once JCPS publishes the revised criteria.',
      'Because Infinity begins in grade 6, some students are already enrolled before high school; families should ask how many external grade-9 seats are expected.',
      'The prior application window ran November 26–December 23, 2025. Treat that only as an advance-planning guide.',
    ],
    academics: [
      'A challenging college-preparatory program in a small setting.',
      'The school’s state report describes an emphasis on a safe, supportive, inclusive community alongside academic excellence.',
      'The small scale is the central differentiator: potential for close relationships, with less curricular breadth than McNair.',
    ],
    programs: ['Small grades 6–12 community', 'Advanced coursework', 'Cambridge program history', 'Close-knit academic culture'],
    questions: ['How many grade-9 seats will be available to outside applicants?', 'Which AP and elective courses will run for the class of 2031?', 'What clubs and teams are active this year?', 'How does counseling support a very small high school cohort?'],
    facts: [
      { label: 'Admissions focus', value: '80% grades + PSAT' },
      { label: 'School model', value: 'Grades 6–12' },
      { label: 'Defining strength', value: 'Small community' },
    ],
    sourceIds: ['jcps-admissions', 'jcboe-admissions-criteria', 'jcps-psat', 'college-board', 'nj-performance'],
  },
  {
    slug: 'innovation-high',
    name: 'Innovation High School',
    shortName: 'Innovation High',
    type: 'Small JCPS project-based STEAM school',
    system: 'Jersey City Public Schools',
    location: '239 Bergen Avenue, Jersey City',
    cost: 'Public · no tuition',
    test: 'No entrance test listed · lottery',
    eligibility: 'JCPS students entering grade 9; must rank Innovation first on the HIP application',
    accent: 'teal',
    summary: 'A small college-preparatory high school built around hands-on projects and STEAM, offering a markedly different experience from both the large district schools and exam-based magnets.',
    bestFor: 'Students who learn by building, presenting, collaborating, and connecting subjects—and who want a smaller public-school setting.',
    tradeoff: 'Innovation must be the first choice on the HIP application and admission uses a lottery; families should also compare its smaller course and activity menu with larger schools.',
    admissionsStatus: 'JCPS has not yet posted the 2027–28 HIP calendar. In the latest cycle, Innovation could only be ranked first and used a lottery process.',
    admissions: [
      'Innovation is part of the district’s High School Initiative Program, or HIP, application rather than the McNair/Infinity application.',
      'The latest official guidance says Innovation may only be selected as the applicant’s first choice and uses a lottery process.',
      'The prior HIP fair was January 31, 2026, and the application ran February 2–27. Treat those dates as planning references until JCPS publishes the class-of-2031 calendar.',
      'The HIP application also asks students to consider a home-school pathway; review all three choices before submitting.',
    ],
    academics: [
      'The district describes Innovation as college preparatory, hands-on, project-based, and focused on science, technology, engineering, art, and mathematics.',
      'Innovation participates in the district’s CISCO Network Academy pathway, which can lead toward CCNA-aligned coursework.',
      'Because the school is small, families should verify which advanced, arts, language, and elective courses will run for the class of 2031.',
    ],
    programs: ['Project-based learning', 'STEAM focus', 'CISCO Network Academy', 'Robotics and technology', 'Small-school community'],
    questions: ['How is the lottery conducted and how many ninth-grade seats are expected?', 'What does a typical interdisciplinary project look like?', 'Which AP, arts, and language courses will run?', 'What happens if Innovation is not selected in the lottery?'],
    facts: [
      { label: 'Admissions route', value: 'HIP first-choice lottery' },
      { label: 'School model', value: 'Small · grades 9–12' },
      { label: 'Defining strength', value: 'Project-based STEAM' },
    ],
    sourceIds: ['jcps-hip', 'innovation-home', 'jcps-cte', 'nj-performance'],
  },
  {
    slug: 'liberty-high',
    name: 'Liberty High School',
    shortName: 'Liberty High',
    type: 'Small JCPS interview-based high school',
    system: 'Jersey City Public Schools',
    location: '299 Sip Avenue, Jersey City',
    cost: 'Public · no tuition',
    test: 'No entrance test listed · interview required',
    eligibility: 'JCPS students entering grade 9; must rank Liberty first on the HIP application',
    accent: 'blue',
    summary: 'A small public high school designed as an alternative to Jersey City’s large comprehensive schools, with a family-like atmosphere and college-and-career preparation.',
    bestFor: 'Students who want teachers and classmates to know them well while retaining access to public-school academics, career courses, and district opportunities.',
    tradeoff: 'Liberty must be the first HIP choice and requires an interview; a small school may offer fewer sections, teams, and electives than a comprehensive campus.',
    admissionsStatus: 'JCPS has not yet posted the 2027–28 HIP calendar. The latest official process required a first-choice ranking and an interview.',
    admissions: [
      'Liberty is included in the single JCPS HIP application alongside the district academies and Innovation.',
      'The latest official guidance says Liberty may only be selected as the first choice and requires an interview.',
      'The prior application ran February 2–27, 2026, after a January 31 HIP fair. Those dates are not confirmed for 2027–28.',
      'Use the interview to explain why a small environment is a good fit and to ask how placement decisions and the home-school fallback work.',
    ],
    academics: [
      'Liberty describes its program as rigorous college-and-career preparation in a small learning environment.',
      'The school highlights Advanced Placement access, while JCPS lists CISCO Network Academy coursework and career electives connected to Liberty.',
      'District programs can broaden the experience, but families should verify daily travel, scheduling, and seat availability.',
    ],
    programs: ['Small learning environment', 'Advanced Placement coursework', 'CISCO Network Academy', 'Business and ProStart electives', 'College and career readiness'],
    questions: ['What is the interview format and what is the school looking for?', 'How many ninth-grade seats are available?', 'Which AP and CTE courses will run next year?', 'How do students access districtwide arts, athletics, and early-college options?'],
    facts: [
      { label: 'Admissions route', value: 'HIP + interview' },
      { label: 'School model', value: 'Small · grades 9–12' },
      { label: 'Defining strength', value: 'Family-like setting' },
    ],
    sourceIds: ['jcps-hip', 'liberty-home', 'jcps-cte', 'nj-performance'],
  },
  {
    slug: 'high-tech-high',
    name: 'High Tech High School',
    shortName: 'High Tech High',
    type: 'Selective county CTE magnet',
    system: 'Hudson County Schools of Technology',
    location: '1 High Tech Way, Secaucus',
    cost: 'Public · no tuition',
    test: 'No entrance test currently listed',
    eligibility: 'Full-time Hudson County residents in grade 8 on September 1, 2026',
    accent: 'teal',
    summary: 'A modern countywide magnet where the academy and major are central to four years of high school—not simply an extracurricular theme.',
    bestFor: 'Students ready to make a meaningful commitment to biomedical science, environmental science, design, computing, media, culinary arts, or performing arts.',
    tradeoff: 'A student should genuinely want the selected program of study; the Secaucus commute also deserves a realistic trial run.',
    admissionsStatus: 'HCST has published the 2027–28 calendar: the application opens October 5, 2026 and is due November 13, with counselor submissions and the required student portfolio due December 23, 2026.',
    admissions: [
      'The student must be in grade 8 as of September 1, 2026, and the student and parent/guardian must be full-time Hudson County residents.',
      'HCST uses one application process for all its full-time programs; families may list a second-choice major, but HCST notes offers are rarely made through that option.',
      'For 2027–28 the application opens October 5, 2026 at 4:00 p.m. and is due November 13; teacher recommendations are due November 30, and school-counselor submissions and the required student portfolio are both due December 23, 2026.',
      'Applications are reviewed on academic record, attendance, a teacher recommendation, an essay, the student portfolio (link emailed November 16), and an audition for qualifying majors (December 5 or 12, 2026). High Tech open houses are September 29–30, 2026 at 5:30 p.m.',
    ],
    academics: [
      'A full college-preparatory core sits alongside career and technical education.',
      'The school lists AP options across English, history, science, and math, including Calculus AB/BC and multiple lab sciences.',
      'Dual-enrollment and LEAP opportunities can add college-level coursework, depending on program and availability.',
    ],
    programs: ['Biomedical Sciences', 'Culinary Arts', 'Design & Fabrication', 'Environmental Science', 'Media & Visual Arts', 'Performing Arts'],
    questions: ['What is the four-year course sequence for the intended major?', 'Can students change majors, and when?', 'What portfolio or audition materials are required?', 'What transportation is available from your part of Jersey City?'],
    facts: [
      { label: 'Admissions pool', value: 'All Hudson County' },
      { label: 'School model', value: 'Academy + CTE major' },
      { label: 'Defining strength', value: 'Deep specialization' },
    ],
    sourceIds: ['hcst-admissions', 'high-tech-academies', 'high-tech-academics', 'nj-performance'],
  },
  {
    slug: 'county-prep',
    name: 'County Prep High School',
    shortName: 'County Prep',
    type: 'Selective county CTE magnet',
    system: 'Hudson County Schools of Technology',
    location: '525 Montgomery Street, Jersey City',
    cost: 'Public · no tuition',
    test: 'No entrance test currently listed',
    eligibility: 'Full-time Hudson County residents in grade 8 on September 1, 2026',
    accent: 'blue',
    summary: 'A career-focused county magnet with an unusually practical range of health, professional-services, creative, and technology majors in Jersey City.',
    bestFor: 'Students excited by a specific applied path such as medical science, cybersecurity, business, culinary arts, cosmetology, fashion, media, or photography.',
    tradeoff: 'The strongest reason to choose County Prep is major fit—not a generic desire for a selective school.',
    admissionsStatus: 'HCST has published the 2027–28 calendar. County Prep open houses are September 22, 24, and October 1, 2026; the application opens October 5 and is due November 13, 2026.',
    admissions: [
      'County Prep and High Tech share one HCST application process for 2027–28.',
      'Applicants must be in grade 8 as of September 1, 2026 and be full-time Hudson County residents, and the chosen CTE major is a core placement factor—so study programs before submitting preferences.',
      'The application opens October 5, 2026 at 4:00 p.m. and is due November 13; teacher recommendations are due November 30, and school-counselor submissions and the required student portfolio are both due December 23, 2026.',
      'County Prep open houses are September 22, 24, and October 1, 2026 at 5:00 p.m.; auditions for qualifying majors are December 5 or 12, 2026.',
    ],
    academics: [
      'College-preparatory requirements run alongside four years of vocational classes.',
      'County Prep currently lists AP courses across English, history, science, math, Spanish, computer science, seminar, and research.',
      'The school also publishes a broad elective menu spanning science, arts, business, media, psychology, and social studies.',
    ],
    programs: ['Medical Science', 'Kinesiology & Exercise Science', 'Networking & Cybersecurity', 'Business', 'Culinary Arts', 'Cosmetology', 'Fashion Design', 'Graphic & Media programs'],
    questions: ['Which certifications or college credits can the chosen major lead to?', 'How much of each day is spent in the major by grade?', 'What internships or work-based learning are typical?', 'How competitive is placement in the preferred major?'],
    facts: [
      { label: 'Admissions pool', value: 'All Hudson County' },
      { label: 'School model', value: 'Career-major CTE' },
      { label: 'Defining strength', value: 'Practical pathways' },
    ],
    sourceIds: ['hcst-admissions', 'county-prep-programs', 'county-prep-academics', 'county-prep-ap', 'nj-performance'],
  },
  {
    slug: 'university-academy-charter',
    name: 'University Academy Charter High School',
    shortName: 'University Academy',
    type: 'Small public charter high school',
    system: 'Independent public charter school',
    location: '275 West Side Avenue, Jersey City',
    cost: 'Public charter · no tuition',
    test: 'No entrance test · lottery if oversubscribed',
    eligibility: 'Jersey City students entering grades 9–12, subject to available seats',
    accent: 'gold',
    summary: 'A small, open-enrollment public charter high school combining close classes, service learning, journalism, and a growing range of advanced and applied courses.',
    bestFor: 'Students seeking a small charter-school community with service learning, student voice, and an expanding menu of technology and applied electives.',
    tradeoff: 'The 2027–28 ninth-grade deadline is not yet posted, and a smaller school cannot match every course, team, or club offered by a large campus.',
    admissionsStatus: 'The 2027–28 deadline is not yet posted. The latest full cycle used a December 18 deadline and January public lottery; current-year applications remain available for some grades.',
    admissions: [
      'UACHS is a tuition-free, open-enrollment public charter school and does not select students by academic or athletic ability.',
      'When applications exceed available seats, admission is determined through a public lottery and remaining applicants move to a wait list.',
      'For 2026–27, the new-student deadline was December 18, 2025, and the lottery was January 14, 2026. Use that timing only to prepare for the next announcement.',
      'The school accepts completed applications by email, fax, mail, or in person; confirm the class-of-2031 form and deadline before submitting.',
    ],
    academics: [
      'The current school profile describes about 441 students and classes of roughly 20 or fewer, with service learning in every grade and a senior capstone.',
      'The school highlights an award-winning student journalism program and community-based learning.',
      'Its current course catalog includes AP courses, engineering design, robotics, drones, agricultural science and food security, entrepreneurship, journalism, and dual-credit options.',
    ],
    programs: ['Service-learning capstone', 'Student Voice journalism', 'AP coursework', 'Robotics and drones', 'Engineering design', 'Agricultural science'],
    questions: ['When will the 2027–28 application and lottery calendar be posted?', 'How many ninth-grade seats are expected?', 'Which AP and dual-credit courses will run?', 'How are service-learning projects built into the weekly schedule?'],
    facts: [
      { label: 'Admissions route', value: 'Open enrollment / lottery' },
      { label: 'School model', value: 'Small · grades 9–12' },
      { label: 'Defining strength', value: 'Service + student voice' },
    ],
    sourceIds: ['uachs-apply', 'uachs-profile', 'uachs-courses', 'nj-performance'],
  },
  {
    slug: 'beloved-community-charter',
    name: 'BelovED Community Charter School',
    shortName: 'BelovED Charter',
    type: 'Public K–12 charter school',
    system: 'Independent public charter school',
    location: '531 Grand Street, Jersey City · high school campus',
    cost: 'Public charter · no tuition',
    test: 'No entrance test · lottery',
    eligibility: 'Jersey City students; grade-level openings determine available seats',
    accent: 'orange',
    summary: 'A tuition-free K–12 charter option with a structured, data-informed instructional model and a separate high-school program in Jersey City.',
    bestFor: 'Students who respond well to a structured charter-school culture, consistent expectations, technology-supported teaching, and continuity within a K–12 community.',
    tradeoff: 'The school’s detailed 2026–27 high-school curriculum page is still under construction, so families should request the current course catalog and confirm ninth-grade seat availability.',
    admissionsStatus: 'Confirmed: applications for 2027–28 open October 15, 2026, close January 15, 2027, and enter the annual January lottery.',
    admissions: [
      'BelovED’s 2027–28 application window is confirmed for October 15, 2026 through January 15, 2027.',
      'Admission is through an annual January lottery; applications submitted after January 15 move to the wait list in application order.',
      'BelovED lists two grades 9–12 open houses: a virtual session on Thursday, October 22, 2026 at 5:00 p.m., and an in-person session on Thursday, January 28, 2027 at 5:30 p.m. No appointment is needed. The school sends the virtual link to applicants the day before, and anyone can request it from the registrar. The January 28 session falls after the January 15 lottery deadline.',
      'The school reports that it admits a smaller number of students in grades beyond kindergarten, so families should ask specifically about ninth-grade openings.',
      'Wait lists expire at the end of the school year, meaning families must reapply for a later year if no seat becomes available.',
    ],
    academics: [
      'BelovED describes a New Jersey standards-aligned, data-driven instructional model using active lessons, technology, and frequent teacher coaching.',
      'Current high-school summer materials show honors, Pre-AP, AP Language, and AP Literature pathways in English.',
      'Because the detailed 2026–27 high-school curriculum page is not yet complete, families should verify the full math, science, arts, language, counseling, and extracurricular program directly.',
    ],
    programs: ['K–12 continuity', 'Structured charter model', 'Honors and advanced English', 'Technology-supported instruction', 'High-school athletics'],
    questions: ['How many external ninth-grade seats will enter the lottery?', 'When will the complete 2026–27 high-school curriculum be published?', 'Which AP, arts, language, and STEM courses run?', 'What are the school day, homework, discipline, and support expectations?'],
    facts: [
      { label: 'Application window', value: 'Oct 15–Jan 15' },
      { label: 'School model', value: 'Charter · grades K–12' },
      { label: 'Defining strength', value: 'Structured continuity' },
    ],
    sourceIds: ['beloved-apply', 'beloved-visit', 'beloved-curriculum', 'nj-performance'],
  },
  {
    slug: 'saint-dominic-academy',
    name: 'Saint Dominic Academy',
    shortName: 'Saint Dominic Academy',
    type: 'Private all-girls Catholic college prep',
    system: 'Independent Catholic school',
    location: '2572 John F. Kennedy Boulevard, Jersey City',
    cost: '$19,500 tuition + $500 registration for 2026–27',
    test: 'HSPT/COOP in latest published process',
    eligibility: 'Girls applying to grades 7–12; freshman process shown here',
    accent: 'berry',
    summary: 'A small, values-centered all-girls environment with college preparation, close faculty relationships, leadership opportunities, and a medical pathway.',
    bestFor: 'Students who want a small all-girls community, Catholic education, and substantial personal attention—with MEDQUEST as a notable health-care option.',
    tradeoff: 'Tuition, Catholic formation, and the smaller course-and-activity scale are major fit questions, not footnotes.',
    admissionsStatus: 'Applications are available through the school. The September 27, 2026 fall open house has passed and no later open house is posted; families can schedule a tour or a DOMS for a Day student visit. Full class-of-2031 deadlines are not yet posted.',
    admissions: [
      'The school’s current application page calls for an application account, transcript, recommendation letter, and an entrance/placement exam for eighth-grade applicants in its latest published cycle.',
      'The detailed school profile describes admission based on the formal application, recommendations, prior school records and standardized scores, including HSPT for high school.',
      'The September 27 open house has passed. Schedule a campus tour or a DOMS for a Day student visit through the school’s enrollment portal to test the all-girls, small-school, and faith-centered fit.',
      'The archdiocesan COOP/HSPT for current eighth graders is Friday, November 6, 2026, and registration closes October 23. Saint Dominic’s own page still describes the prior cycle, so confirm with admissions that this is its class-of-2031 test.',
      'Ask admissions to confirm the class-of-2031 testing, scholarship, financial-aid, and response deadlines before acting.',
    ],
    academics: [
      'College-preparatory, honors, and AP coursework in a small-class environment.',
      'MEDQUEST is the school’s distinctive medical and health-care exploration pathway.',
      'The school promotes dual-enrollment, STEM, engineering/robotics, arts, clubs, athletics, service, and leadership.',
    ],
    programs: ['MEDQUEST health pathway', 'Honors and AP coursework', 'Dual enrollment', 'Fine and performing arts', 'Leadership and service', 'All-girls learning environment'],
    questions: ['What will 2027–28 tuition and total fees be after aid?', 'Which AP and dual-enrollment courses will run?', 'What does Catholic formation look like day to day?', 'How do MEDQUEST admission and scheduling work?'],
    facts: [
      { label: '2026–27 tuition', value: '$19,500 + fees' },
      { label: 'School model', value: 'Girls · grades 7–12' },
      { label: 'Defining strength', value: 'Small, supportive setting' },
    ],
    sourceIds: ['sda-home', 'sda-apply', 'sda-tuition', 'coop-hspt'],
  },
  {
    slug: 'hudson-catholic',
    name: 'Hudson Catholic Regional High School',
    shortName: 'Hudson Catholic',
    type: 'Private coeducational Catholic college prep',
    system: 'Catholic school · Archdiocese of Newark',
    location: '790 Bergen Avenue, Jersey City',
    cost: '$13,000 tuition + required fees for 2026–27',
    test: 'HSPT required for incoming freshmen and aid consideration',
    eligibility: 'Students applying for grade 9; transfer applications also considered',
    accent: 'teal',
    summary: 'A coeducational Catholic high school with college preparation, faith formation, athletics, arts, and an applied course menu that includes health, law, coding, and business.',
    bestFor: 'Students who want a coed Catholic community, a broad mix of academics and activities, and a Jersey City campus with a lower published tuition than the other private options in this guide.',
    tradeoff: 'Tuition and required fees remain substantial, and families should confirm Hudson Catholic’s Class of 2031 test and application deadlines directly with admissions.',
    admissionsStatus: 'Applications are available. The current page lists a November 6, 2026 HSPT labeled 2026–27, the same label the Archdiocese uses for this fall’s test. HSPT registration closes October 23; confirm every class-of-2031 deadline with admissions.',
    admissions: [
      'Applicants complete the school application and submit sixth-, seventh-, and current eighth-grade report cards plus two teacher recommendations.',
      'Hudson Catholic requires incoming freshmen to take the Archdiocese of Newark HSPT and says the test is also required for scholarship and financial-aid consideration.',
      'The admissions office schedules an interview after receiving a completed application.',
      'The school’s current page lists November 6, 2026 for the HSPT and calls the cycle 2026–27. The Archdiocese’s official testing program uses the same “2026–2027” label for its November 6, 2026 test for current eighth graders, with registration closing October 23. Still confirm Hudson Catholic’s Class of 2031 deadlines with admissions.',
    ],
    academics: [
      'The most recently published course list combines traditional college-preparatory subjects with honors, AP, and dual-credit courses.',
      'Applied electives include anatomy, medical arts, sports medicine, forensic science, criminal law, coding, finance, graphic design, photography and podcasting, and theater.',
      'Catholic religion courses, service, athletics, and extracurricular activities are part of the overall student experience.',
    ],
    programs: ['Honors, AP, and dual-credit courses', 'Medical and health electives', 'Coding, finance, and criminal law', 'Fine and performing arts', 'Catholic formation', 'Athletics'],
    questions: ['Can admissions confirm every Class of 2031 date in writing?', 'What will 2027–28 tuition and total required fees be after aid?', 'Which AP and dual-credit courses will run?', 'How do faith, service, and religion classes shape the school week?'],
    facts: [
      { label: '2026–27 tuition', value: '$13,000 + fees' },
      { label: 'School model', value: 'Coed · grades 9–12' },
      { label: 'Defining strength', value: 'Catholic + applied breadth' },
    ],
    sourceIds: ['hudson-catholic-apply', 'hudson-catholic-tuition', 'hudson-catholic-courses', 'coop-hspt'],
  },
  {
    slug: 'saint-peters-prep',
    name: 'Saint Peter’s Preparatory School',
    shortName: 'Saint Peter’s Prep',
    type: 'Private all-boys Jesuit Catholic college prep',
    system: 'Independent Jesuit Catholic school',
    location: '144 Grand Street, Jersey City',
    cost: '$25,901 tuition + $1,350 mandatory fees for 2026–27',
    test: 'HSPT or an accepted equivalent',
    eligibility: 'Young men applying to grade 9',
    accent: 'blue',
    summary: 'A large, academically broad Jesuit high school for boys, combining extensive advanced coursework with athletics, arts, service, retreats, and four years of structured guidance.',
    bestFor: 'Students who want a demanding, activity-rich all-boys environment and whose family values Jesuit formation, service, reflection, and a large regional community.',
    tradeoff: 'It is the highest published-cost option in this guide before aid, and the scale, workload, all-boys setting, and Catholic mission should all be tested through a visit.',
    admissionsStatus: 'Confirmed for the Class of 2031: applications opened September 1, 2026; HSPT is November 6; complete by December 11 for a January decision and timely aid review.',
    admissions: [
      'The Class of 2031 application and Freshman for a Day calendar opened September 1, 2026; visits begin September 21 and the fall open house is October 18.',
      'The HSPT is November 6, with a November 14 makeup date at other test sites (Prep is not a makeup site). Archdiocesan HSPT registration closes October 23. Prep also accepts the SSAT, ISEE, TACHS, or an equivalent test.',
      'A complete application by December 11 includes the online form, test, official transcript, teacher recommendation, and essay.',
      'December 11 is also the financial-aid deadline for a decision with the admission letter. Decisions are mailed January 14 and emailed January 15, 2027.',
    ],
    academics: [
      'Prep offers a broad college-preparatory program across English, mathematics, history, science, world languages, theology, arts, computer science, health, and physical education.',
      'The school reports 51 honors and AP-level courses, with advanced placement opportunities available throughout a student’s four years.',
      'Every student participates in a four-year group guidance curriculum alongside individual academic, personal, and college counseling.',
    ],
    programs: ['51 honors and AP-level courses', 'Four-year guidance curriculum', 'Jesuit service and retreats', 'Fine and performing arts', 'Global initiatives', 'Extensive athletics and clubs'],
    questions: ['What is the likely four-year net cost after aid?', 'How much homework is typical in each course level?', 'How does the all-boys Jesuit model feel in daily life?', 'Which activities are realistic alongside the intended academic load and commute?'],
    facts: [
      { label: 'Complete by', value: 'December 11, 2026' },
      { label: 'School model', value: 'Boys · grades 9–12' },
      { label: 'Defining strength', value: 'Jesuit breadth + community' },
    ],
    sourceIds: ['spprep-dates', 'spprep-tuition', 'spprep-academics', 'coop-hspt'],
  },
];

export const jcpsPathways = [
  {
    school: 'William L. Dickinson High School',
    academy: 'Academy of the Sciences',
    location: '2 Palisade Avenue',
    programs: ['Green Construction / House Renovation', 'Air Force JROTC', 'Applied, Physical & Health Sciences', 'Health and Medical Careers', 'Robotics Engineering', 'Information Technology'],
    bestFor: 'Students seeking science, health, technology, construction, or JROTC pathways in a large comprehensive school.',
  },
  {
    school: 'James J. Ferris High School',
    academy: 'Academy of International Enterprise',
    location: '35 Colgate Avenue',
    programs: ['Finance', 'Marketing', 'Hospitality & Tourism'],
    bestFor: 'Students interested in business, marketing, hospitality, entrepreneurship, and an international-enterprise theme.',
  },
  {
    school: 'Abraham Lincoln High School',
    academy: 'Academy of Governance & Social Sciences',
    location: '60 Crescent Street',
    programs: ['Cosmetology & Barbering', 'Culinary Arts & Restaurant Management', 'Legal Profession & Public Safety', 'Army JROTC'],
    bestFor: 'Students drawn to public service, law, culinary arts, cosmetology, barbering, or military leadership.',
  },
  {
    school: 'Henry Snyder High School',
    academy: 'Academy of the Arts',
    location: '239 Bergen Avenue',
    programs: ['Fashion Design', 'Graphic & Commercial Design', 'Dance'],
    bestFor: 'Students who want an arts-centered pathway while remaining in a comprehensive public-school setting.',
  },
];

export const districtwidePathways = [
  {
    name: 'Jersey City Arts Program',
    detail: 'Visual art, theater, vocal music, and instrumental music pathways use portfolios, interviews, or auditions and may include instruction at NJCU.',
  },
  {
    name: 'B.E.S.T.',
    detail: 'Broadcasting & Electronic Storytelling trains students in directing, scriptwriting, camera, sound, on-air work, graphics, editing, podcasts, and production.',
  },
  {
    name: 'Early College with HCCC',
    detail: 'Eligible juniors and seniors may take up to 18 college credits per academic year through Hudson County Community College.',
  },
];

export type TimelineItem = {
  date: string;
  title: string;
  body: string;
  schools: string[];
  status: 'Confirmed' | 'Expected' | 'Action';
  sourceId?: string;
};

export const timeline: TimelineItem[] = [
  {
    date: 'Now · September',
    title: 'Build one calendar across every application system',
    body: 'Confirm the PSAT 8/9 plan for McNair and Infinity, open the Saint Peter’s Prep application, register for visits, and make a document checklist for public, charter, county, and Catholic applications.',
    schools: ['All schools'],
    status: 'Action',
    sourceId: 'jcps-psat',
  },
  {
    date: 'September 1 · open now',
    title: 'Saint Peter’s Prep application and visit calendar open',
    body: 'The Class of 2031 application is open. Freshman for a Day visits begin September 21, and the fall open house is October 18 from 1–4 p.m.',
    schools: ['Saint Peter’s Prep'],
    status: 'Confirmed',
    sourceId: 'spprep-dates',
  },
  {
    date: 'Sunday, September 27 · 11 a.m.–1 p.m.',
    title: 'Saint Dominic Academy fall open house',
    body: 'Meet admissions, tour the campus, and ask for the class-of-2031 HSPT, application, scholarship, and financial-aid calendar.',
    schools: ['Saint Dominic'],
    status: 'Confirmed',
    sourceId: 'sda-home',
  },
  {
    date: 'September 22 – October 1',
    title: 'HCST open houses for County Prep and High Tech',
    body: 'County Prep hosts open houses September 22, 24, and October 1 at 5:00 p.m.; High Tech hosts September 29 and 30 at 5:30 p.m. Attend to compare majors before the October 5 application opening.',
    schools: ['High Tech', 'County Prep'],
    status: 'Confirmed',
    sourceId: 'hcst-admissions',
  },
  {
    date: 'October 1–30',
    title: 'Fall in-school PSAT 8/9 testing window',
    body: 'College Board’s national in-school window is confirmed. Your school selects its local date. Depending on submission date, fall scores are scheduled for student release from October 22 through November 12.',
    schools: ['McNair', 'Infinity'],
    status: 'Confirmed',
    sourceId: 'college-board',
  },
  {
    date: 'October 15, 2026',
    title: 'BelovED’s 2027–28 application opens',
    body: 'Apply by January 15, 2027 to enter the annual lottery. Ask admissions how many ninth-grade seats are expected for students entering from outside BelovED.',
    schools: ['BelovED Charter'],
    status: 'Confirmed',
    sourceId: 'beloved-apply',
  },
  {
    date: 'Sunday, October 18 · 1–4 p.m.',
    title: 'Saint Peter’s Prep fall open house',
    body: 'Tour the campus and test the academic scale, Jesuit mission, commute, activities, and all-boys environment before the November HSPT.',
    schools: ['Saint Peter’s Prep'],
    status: 'Confirmed',
    sourceId: 'spprep-dates',
  },
  {
    date: 'October 5 – December 23',
    title: 'HCST application window for High Tech and County Prep',
    body: 'The application opens October 5 (4:00 p.m.) and is due November 13. Teacher recommendations are due November 30; portfolio links are emailed November 16, with counselor submissions and the student portfolio due December 23. Auditions for qualifying majors are December 5 and 12.',
    schools: ['High Tech', 'County Prep'],
    status: 'Confirmed',
    sourceId: 'hcst-admissions',
  },
  {
    date: 'Thursday, October 22 · 5:00 p.m.',
    title: 'BelovED grades 9–12 virtual open house',
    body: 'BelovED emails the link to applicants the day before; other families can request it from the registrar. This is the only grades 9–12 open house before the January 15 lottery deadline.',
    schools: ['BelovED Charter'],
    status: 'Confirmed',
    sourceId: 'beloved-visit',
  },
  {
    date: 'Friday, October 23',
    title: 'Last day to register for the Catholic high-school HSPT',
    body: 'Register at njcoopexam.org for the November 6 archdiocesan HSPT. Students at participating Catholic elementary schools follow their school’s process, which must be finished by October 9. Requests for extended testing time are due October 20.',
    schools: ['Saint Peter’s Prep', 'Hudson Catholic', 'Saint Dominic'],
    status: 'Confirmed',
    sourceId: 'coop-hspt',
  },
  {
    date: 'Friday, November 6',
    title: 'Catholic high-school HSPT date',
    body: 'The Archdiocese of Newark’s official testing program confirms the November 6 HSPT for current eighth graders, with a November 14 makeup at select sites. Saint Peter’s Prep confirms the same date. Hudson Catholic lists it under the same “2026–27” label the Archdiocese uses; confirm its Class of 2031 instructions directly.',
    schools: ['Saint Peter’s Prep', 'Hudson Catholic'],
    status: 'Confirmed',
    sourceId: 'coop-hspt',
  },
  {
    date: 'Fall · exact date pending',
    title: 'Complete Saint Dominic testing and application steps',
    body: 'Saint Dominic’s latest guidance used the COOP/HSPT for eighth-grade applicants, and this fall’s archdiocesan COOP/HSPT is November 6. Its own page still describes the prior cycle, so confirm the class-of-2031 test and document deadlines directly with admissions.',
    schools: ['Saint Dominic'],
    status: 'Action',
    sourceId: 'sda-apply',
  },
  {
    date: 'Late fall · exact date pending',
    title: 'Watch for University Academy’s new-student deadline',
    body: 'The prior UACHS cycle closed December 18 and held its public lottery January 14. Prepare the form early, but wait for the school to publish the 2027–28 dates.',
    schools: ['University Academy'],
    status: 'Expected',
    sourceId: 'uachs-apply',
  },
  {
    date: 'Late November–December · planning estimate',
    title: 'Likely McNair and Infinity application period',
    body: 'Last cycle ran November 26–December 23. The 2027–28 dates are not yet announced, so prepare recommendations and records early but wait for the official window.',
    schools: ['McNair', 'Infinity'],
    status: 'Expected',
    sourceId: 'jcps-admissions',
  },
  {
    date: 'Friday, December 11',
    title: 'Complete Saint Peter’s Prep application and financial aid',
    body: 'Submit the application, test, transcript, teacher recommendation, and essay by this date for a January decision. Financial-aid applications are also due for an aid decision with admission.',
    schools: ['Saint Peter’s Prep'],
    status: 'Confirmed',
    sourceId: 'spprep-dates',
  },
  {
    date: 'Friday, January 15, 2027',
    title: 'BelovED lottery deadline',
    body: 'Applications received by January 15 participate in the annual lottery. Later applications join the wait list in submission order.',
    schools: ['BelovED Charter'],
    status: 'Confirmed',
    sourceId: 'beloved-apply',
  },
  {
    date: 'January 14–15, 2027',
    title: 'Saint Peter’s Prep decisions',
    body: 'Decision letters are mailed January 14 and emailed January 15. Compare the offer with financial aid, commute, workload, mission, and the student’s other options.',
    schools: ['Saint Peter’s Prep'],
    status: 'Confirmed',
    sourceId: 'spprep-dates',
  },
  {
    date: 'Thursday, January 28, 2027 · 5:30 p.m.',
    title: 'BelovED grades 9–12 open house',
    body: 'No appointment is needed. This in-person open house comes after the January 15 lottery deadline, so do not wait for it to apply if you want a place in the lottery. The October 22 virtual session is the earlier option.',
    schools: ['BelovED Charter'],
    status: 'Confirmed',
    sourceId: 'beloved-visit',
  },
  {
    date: 'Late January–February · planning estimate',
    title: 'Likely JCPS HIP fair, application, interviews, and lottery',
    body: 'The latest cycle held the fair January 31 and accepted applications February 2–27 for Dickinson, Ferris, Lincoln, Snyder, Innovation, Liberty, JC Arts, and B.E.S.T. Wait for the 2027–28 calendar before acting.',
    schools: ['Innovation', 'Liberty', 'JCPS academies'],
    status: 'Expected',
    sourceId: 'jcps-hip',
  },
  {
    date: 'Winter 2027',
    title: 'Decisions, responses, and financial aid',
    body: 'Track every portal and personal-email inbox. Compare offers alongside transportation, daily program fit, total private-school cost, and aid—not rankings alone.',
    schools: ['All schools'],
    status: 'Expected',
  },
];

export function getSchool(slug: string) {
  return schools.find((school) => school.slug === slug);
}

export function getSources(ids: string[]) {
  return ids.map((id) => sources.find((source) => source.id === id)).filter(Boolean) as Source[];
}
